[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nixPkgs = ["nodejs", "npm"]

[deploy]
workingDirectory = "backend"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 